# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230430-192738-bipartite-detail

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  # "case_sensitive": false
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 6
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 30
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 3
  epochs: 60
  constrain_similarities: true

#     epochs: 100
#     constrain_similarities: true
# https://github.com/RasaHQ/rasa-demo/blob/main/domain.yml
# https://github.com/karim-aloulou/Espritchatbot
# https://github.com/vuxuanhoang000/RASA/tree/main/Digestive-Healthcare-Chatbot/data
# https://github.com/haotran0103/chatbot_rasa/blob/master/data/stories.yml
# phuong_thuc_tuyen_sinh
# gt_QHT93
# gt_QHT13
# hp_QHT98
# gt_QHT03
# hp_QHT43
# chnn_QHT12
# chnn_QHT20
# chnn_QHT96